config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :playlists
  resources :mediums
  resources :devices
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/medium.rb
class Medium < ApplicationRecord
    has_many :playlist_items, dependent: :destroy
    has_many :playlists, through: :playlist_items
    has_many :medium_devices
    has_many :devices, through: :medium_devices
    scope :filter_by_title, ->(title) { where("LOWER(title) LIKE ?", "%#{title.downcase}%") if title.present? }
    # validates :title, presence: true, length: {minimum: 6, maximum: 100}
    # validates :description, presence: true, length: {minimum: 6, maximum: 100}
    # validate :valid_content_url

    private
  
    def valid_content_url
      if content_url.present?
        uri = URI.parse(content_url)
        unless uri.is_a?(URI::HTTP) && !uri.host.nil?
          errors.add(:content_url, 'is not a valid URL')
        end
      else
        errors.add(:content_url, 'can\'t be blank')
      end
    rescue URI::InvalidURIError
      errors.add(:content_url, 'is not a valid URL')
    end
end

app/controllers/mediums_controller.rb
class MediumsController < ApplicationController

    before_action :set_medium, only: [:edit, :show, :update, :destroy]
    before_action :require_user, expect: [:show]


    def index 
        @medium = Medium.all
        @medium = @medium.filter_by_title(params[:search]) if params[:search].present?
    end

    def new 
        @medium = Medium.new 
    end

    def edit

    end

    def create
        @medium = Medium.new
        @medium.assign_attributes(create_params.except(:playlist_ids))
        if @medium.save
            Array(create_params[:playlist_ids]).compact.each do |playlist_id|
              next unless playlist_id.present?
              PlaylistItem.create(medium_id: @medium.id, playlist_id: playlist_id)
            end          
            flash[:notice] = "New medium was added"
            redirect_to mediums_path
        else
            render "new"
        end
    end

    def show 

    end

    def update
        puts "params: #{}"
        if @medium.update(create_params)
            flash[:notice] = "Medium was updated"
            redirect_to @medium
        else 
            render 'edit'
        end
    end

    def destroy
        @medium.destroy
        redirect_to mediums_path
    end  

    private 

    def set_medium
        @medium = Medium.find(params[:id])
    end

    def create_params
        params.permit(:title, :description, :content_url, playlist_ids: []) #:playlist_id)
    end


end

app/helpers/mediums_helper.rb
module MediumsHelper
end

app/views/mediums/_form.html.erb
<% if @medium.errors.any? %>
    <h2>The following errors prevented the medium from being saved:</h2>
    <ul>
        <% @medium.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
        <% end %>
    </ul>
<% end %>


 <%= form_with(url: "/mediums", method: :post, data: {turbo: false}) do |f| %>

    <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </p>

    <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %> 
    </p>

    <p>
    <%= f.label :content_url %> <br>
    <%= f.text_area :content_url %> 
    </p>

    <!-- <p>
        <%= f.label :playlist_id %> <br>
        <%= f.collection_check_boxes :playlist_ids, Playlist.all, :id, :title do |b| %>
            <%= b.check_box %>
            <%= b.label %>
        <% end %>    
    </p>

    <p>
    <%= select "medium", "playlist_ids", Playlist.all.collect { |p| [p.title, p.id] }, { prompt: "Select playlists" }, { multiple: true } %>
    </p> -->

    <p>
    <%= f.submit %>
    </p>

<% end %>

app/views/mediums/edit.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
<h1> Edit the medium </h1> 

<%= render 'form' %>

<%= button_to "Cancel and return to medium", mediums_path, method: :get %>

app/views/mediums/index.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> <!-- Transparent white background and padding for the table -->
<% if logged_in? %>
  <%= link_to "Add a new song", new_medium_path, style: "color: black;" %>
  <br><br>
  <%= form_with(url: mediums_path, method: "get") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search by Title" %>
    <%= submit_tag "Search" %>
  <% end %>
<% end %>

    <h1 style="color: black;">Songs List</h1>

    <table style="width: 40%; color: black; border-collapse: collapse;"> <!-- Black text color for the table -->
        <thead>
            <tr>
                <th style="padding: 10px; text-align: left;">Title</th> 
                <th style="padding: 10px; text-align: left;">Description</th> 
                <th style="text-align: left;">Link to Listen</th> 
                <th style="padding: 20px; text-align: center;">Actions</th> 
            </tr>
        </thead>
        
        <tbody >
            <% @medium.each do |medium| %>
                <tr>
                    <td style="text-align: left;"><strong><%= medium.title %></strong></td> 
                    <td style="text-align: left;"><%= medium.description %></td> 
                    <td style="text-align: left;"><strong><a href="<%= medium.content_url %>" target="_blank">Watch</a></strong></td> 
                    <td style="display: flex;">
                    <form action="<%= medium_path(medium) %>" method="get">
                      <button type="submit" style="color: black; background-color: transparent; border: none;">Show</button>
                    </form>
                    
                    <form action="<%= edit_medium_path(medium) %>" method="get">
                      <button type="submit" style="color: black; background-color: transparent; border: none;">Edit</button>
                    </form>
                  
                    <%= form_tag medium_path(medium), method: :delete, id: "delete-medium-form" do %>
                      <button type="submit" style="color: black; background-color: transparent; border: none;" onclick="return confirmDelete();">Delete</button>
                    <% end %>
                    
                    
                    <script>
                      function confirmDelete() {
                        return confirm("Are you sure you want to delete this medium?");
                      }
                    </script>
                    
                    
                    
                    
                  </td>
                  
                  
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/mediums/new.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
<h1> Add a new medium </h1>

<%= render 'form' %>

<%= button_to "Return to medium", mediums_path, method: :get %>

app/views/mediums/show.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
<h1>Showing medium</h1>

<p><strong>Title: </strong><%= @medium.title %></p>
<p><strong>Description: </strong><%= @medium.description %></p>
<p><strong>URL: </strong><a href="<%= @medium.content_url %>" target="_blank"><%= @medium.content_url %></a></p>
<!-- <p><strong>Playlist: </strong><%= @medium %></p> -->



<%= button_to "Edit", edit_medium_path(@medium), method: :get %> <br>
<%= button_to "Return to medium", mediums_path, method: :get %>