config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :playlists
  resources :mediums
  resources :devices
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    belongs_to :device
    has_many :playlist_items, dependent: :destroy
    belongs_to :user
    has_many :medium, through: :playlist_items
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 6, maximum: 100}
    scope :filter_by_title, ->(title) { where("title LIKE ?", "%#{title}%") if title.present? }

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

    before_action :set_playlist, only: [:show, :edit, :update, :destroy]
    before_action :require_user, expect: [:show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show 
        @playlist = Playlist.includes(:medium).find(params[:id])
    end

    def index
         @playlists = Playlist.paginate(page: params[:page], per_page: 3)
         @playlists = Playlist.filter_by_title(params[:search]).paginate(page: params[:page], per_page: 3)
  
    end


    def new
        @playlist = Playlist.new
    end

    def edit 

    end

    def create
        @playlist = Playlist.new(playlist_params)
        @playlist.user = current_user
        if @playlist.save
            flash[:notice] = "Playlist was created successfully!"
            redirect_to @playlist
        else
            render 'new'
        end

    end

    def update 
        if @playlist.update(playlist_params)
            flash[:notice] = "Article was updated succesfully!"
            redirect_to @playlist
        else
            render 'edit'
        end
    end

    def destroy
        @playlist.destroy
        redirect_to playlists_path
    end
        
    private

    def set_playlist
        @playlist = Playlist.find(params[:id])
    end

    def playlist_params
        params.require(:playlist).permit(:title, :description, :device_id, medium_ids: [])
    end

    def require_same_user
        if current_user != @playlist.user && !current_user.admin?
            flash[:alert] = "You cannot edit or delete others playlists!"
            redirect_to @playlist
        end
    end
end 

app/views/playlists/_form.html.erb
<% if @playlist.errors.any? %>
    <h2>The following errors prevented the playlist from bring saved!</h2>
    <ul>
    <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_with(model: @playlist, local: true) do |f| %>

<p> 
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</p>

<p>
<% if logged_in? %>

    <%= f.label :device_id, "Add to a device" %><br><br>
    <%= f.collection_select :device_id, current_user.devices, :id, :name, { prompt: "Select a device" } %>
    
<% end %>
</p>

<p> 
  <%= f.collection_check_boxes(:medium_ids, Medium.all, :id, :title, { :multiple => true, :size => 5 }) %>
</p>


<p>
    <%= f.submit %>
</p>

<% end %>

app/views/playlists/_playlist.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> <!-- Transparent white background and padding for the table -->

<% if logged_in? %> 

<%= link_to "Create a new playlist", new_playlist_path, style: "color: black;" %> 
<br><br>

<%= form_with(url: playlists_path, method: "get") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by Title" %>
  <%= submit_tag "Search" %>
<% end %>


<% end %>

    <h1 style="color: black;">Playlists listing page</h1>

<style>
    table {
        width: 40%;
        color: black;
        border-collapse: collapse;
    }

    th, td {
        padding: 10px;
        text-align: center;
        border: 1px solid #ddd;
    }

    th {
        background-color: #e6e6fa;
    }

    .actions {
        width: auto;
        text-align: center;
    }

    .actions button {
        color: black;
        background-color: transparent;
        border: none;
        cursor: pointer;
        margin: 0 5px; /* Reduce margin to create space between buttons */
    }

    .button-container {
        display: flex;
        justify-content: center; /* Center align buttons horizontally */
    }

    @media screen and (max-width: 600px) {
        table {
            width: 100%;
        }
    }
</style>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Device</th>
            <th>Actions</th>
            <th>User</th>
        </tr>
    </thead>
    <tbody>
        <% @playlists.each do |playlist| %>
            <tr>
                <td><%= playlist.title %></td>
                <td><%= playlist.description %></td>
                <td><%= playlist.device&.name %></td>
                <td class="actions">
                    <div class="button-container">
                        <%= button_to 'Show', playlist_path(playlist), method: :get %>
                        <% if logged_in? && (playlist.user == current_user || current_user.admin?) %>
                            <%= button_to 'Edit', edit_playlist_path(playlist), method: :get %>
                            <%= button_to 'Delete', playlist_path(playlist), method: :delete, onclick: "return confirm('Are you sure you want to delete this playlist?');" %>
                        <% end %>
                    </div>
                </td>
                <td>
                    <% if playlist.user %>
                        <%= link_to playlist.user.username, user_path(playlist.user) %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

</div>

  

app/views/playlists/edit.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
<h1> Edit playlist </h1>

<%= render 'form' %>

<%= button_to "Cancel and return to playlists", playlists_path, method: :get %>

app/views/playlists/index.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
  <%= will_paginate @playlists, :container => false %>
</div>

<%= render 'playlist' %>

<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
  <%= will_paginate @playlists, :container => false %>
</div>

app/views/playlists/new.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
<h1> Create a new playlist </h1>

<%= render 'form' %>

<%= button_to "Return to playlists", playlists_path, method: :get %>

app/views/playlists/show.html.erb
<div style="background-color: rgba(255, 255, 255, 0.8); padding: 20px;"> 
<h1>Showing playlists details</h1>

<p><strong>Title: </strong><%= @playlist.title %></p>
<p><strong>Description: </strong><%= @playlist.description %></p>
<p><strong>Device: </strong><%= @playlist.device&.name %></p>
<b>User: </b><%= @playlist.user.username if @playlist.user %><br><br> 
<%= link_to gravatar_for(@playlist.user), user_path(@playlist.user) %> <br> <br>
<% if @playlist.medium.present? %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Songs</title>
    <style>
        table {
            border-collapse: collapse;
            width: 35%;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:nth-child(odd) {
            background-color: #ffffff;
        }
        tr:not(:last-child) td {
            border-bottom: 1px solid gray;
        }
    </style>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Link to Listen</th>
            </tr>
        </thead>
        <tbody>
        <% @playlist.medium.each do |medium| %>
            <tr>
                <td><strong><%= medium.title %></strong></td> 
                <td><%= medium.description %></td> 
                <td><strong><a href="<%= medium.content_url %>" target="_blank">Listen</a></strong></td> 
            </tr>
        <% end %>
        </tbody>
    </table>
</body>
</html>
<% end %><br> <br>





<% if logged_in? && (@playlist.user == current_user || current_user.admin?)%>

  <div style="display: flex; justify-content: left;">

    <form action="<%= edit_playlist_path(@playlist) %>" method="get" style="display: inline-block; margin-right: 10px;">
      <button type="submit" class="btn btn-sm" style="background-color: #c3aed6; border-color: #c3aed6; color: white;">Edit</button>
    </form>


<% end %>

    <span></span>
    
    <form action="<%= playlists_path %>" method="get" style="display: inline-block;">
      <button type="submit" class="btn btn-sm" style="background-color: #c3aed6; border-color: #c3aed6; color: white;">Return to playlists</button>
    </form>

  </div>