config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :playlists
  resources :mediums
  resources :devices
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
  <title>PlaylistManager</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', medium: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <button onclick="window.location.href='<%= root_path %>'">Home</button>
      </li>

      <li class="nav-item">
        <button onclick="window.location.href='<%= about_path %>'">About</button>
      </li>

      <li class="nav-item">
        <button onclick="window.location.href='<%= playlists_path %>'">Playlists</button>
      </li>

      <li class="nav-item">
        <button onclick="window.location.href='<%= mediums_path %>'">Songs</button>
      </li>

      <li class="nav-item">
        <button onclick="window.location.href='<%= devices_path %>'">Devices</button>
      </li>

      <li class="nav-item">
        <button onclick="window.location.href='<%= users_path %>'">Users</button>
      </li>

      <% if logged_in? %>

        <li class="nav-item">
          <form action="<%= user_path(current_user) %>">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button type="submit"><%= '(Admin)' if current_user.admin? %><%= current_user.username %></button>
          </form>
        </li>

        <li class="nav-item">
        <form action="<%= logout_path %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button type="submit">Logout</button>
        </form>
      </li>

      <% else %>

        <li class="nav-item">
          <button onclick="window.location.href='<%= login_path %>'">Login</button>
        </li>

        <li class="nav-item">
        <button onclick="window.location.href='<%= signup_path %>'">Signup</button>
      </li>

      <% end %>
    </ul>
  </nav>

  <%= render 'layouts/messages' %>

    <%= yield %>
  </body>

  <% flash.each do |key, value| %>
    <div class="flash <%= key %>">
      <%= value %>
    </div>
  <% end %>
  
</html>